import type { Blocker } from './types';

export const mockBlockers: Blocker[] = [
  {
    id: 'blk-1',
    title: 'Southern Coastal Highway contractor dispute blocking Phase 3',
    description: 'The primary contractor for Phase 3 of the Southern Coastal Highway has filed a variation claim of $1.8B citing force majeure from March flooding. NWA disputes the claim. No work is proceeding on the affected 12km stretch until the contract dispute is resolved. Cabinet directed renegotiation on Apr 20.',
    escalationLevel: 'pm',
    assignedTo: 'Most Hon. Andrew Holness, ON, PC, MP',
    assignedMinistrySlug: 'economic-growth',
    status: 'in_progress',
    createdDate: '2026-03-25',
    linkedType: 'project',
    linkedName: 'Southern Coastal Highway',
    linkedHref: '/ministry/energy-transport/capital',
    activity: [
      { id: 'a1-1', type: 'comment', author: 'Hon. Daryl Vaz, MP', content: 'Contractor submitted variation claim documents. NWA legal team reviewing.', timestamp: '2026-03-25T10:15:00' },
      { id: 'a1-2', type: 'status_change', author: 'System', content: 'Status changed', timestamp: '2026-03-25T10:15:00', previousStatus: 'open', newStatus: 'open' },
      { id: 'a1-3', type: 'comment', author: 'Hon. Audrey Sewell, OJ, CD, JP', content: 'Escalating to PM level — contract value exceeds ministerial threshold for renegotiation.', timestamp: '2026-04-02T14:30:00' },
      { id: 'a1-4', type: 'status_change', author: 'Hon. Audrey Sewell, OJ, CD, JP', content: 'Status changed', timestamp: '2026-04-20T11:00:00', previousStatus: 'open', newStatus: 'in_progress' },
      { id: 'a1-5', type: 'comment', author: 'Most Hon. Andrew Holness, ON, PC, MP', content: 'Cabinet approved renegotiation. AG to draft revised terms. Target completion: May 15.', timestamp: '2026-04-20T12:45:00' },
    ],
  },
  {
    id: 'blk-2',
    title: 'Cornwall Regional Hospital dialysis equipment critically short',
    description: 'Only 2 of 8 dialysis machines are operational at Cornwall Regional. Patients are being turned away and redirected to Kingston, causing severe hardship. Emergency procurement authorized by Cabinet on Apr 20 but supplier lead time is 3 weeks minimum.',
    escalationLevel: 'minister',
    assignedTo: 'Dr. the Hon. Christopher Tufton, CD, MP',
    assignedMinistrySlug: 'health',
    status: 'in_progress',
    createdDate: '2026-04-08',
    linkedType: 'action_item',
    linkedName: 'Hospital equipment procurement working group',
    linkedHref: '/meetings/mtg-2026-04-20',
    activity: [
      { id: 'a2-1', type: 'comment', author: 'Dr. the Hon. Christopher Tufton, CD, MP', content: 'Cornwall Regional down to 2 functioning dialysis machines. Requesting emergency procurement.', timestamp: '2026-04-08T09:00:00' },
      { id: 'a2-2', type: 'comment', author: 'Hon. Fayval Williams, MP', content: 'Finance confirms emergency procurement can bypass standard tender under GPA provisions.', timestamp: '2026-04-15T11:20:00' },
      { id: 'a2-3', type: 'status_change', author: 'Dr. the Hon. Christopher Tufton, CD, MP', content: 'Status changed', timestamp: '2026-04-20T10:40:00', previousStatus: 'open', newStatus: 'in_progress' },
      { id: 'a2-4', type: 'comment', author: 'Dr. the Hon. Christopher Tufton, CD, MP', content: 'Purchase order issued to Fresenius Medical Care. Expected delivery May 11-14.', timestamp: '2026-04-22T15:00:00' },
    ],
  },
  {
    id: 'blk-3',
    title: 'National Digital ID pilot stalled — vendor API integration failing',
    description: 'The NIRA vendor\'s biometric API is returning >15% false rejection rates during the St. Catherine pilot. NIRA has paused enrollment until the vendor delivers a patch. This blocks the broader Digital Transformation Strategy timeline.',
    escalationLevel: 'pm',
    assignedTo: 'Most Hon. Andrew Holness, ON, PC, MP',
    assignedMinistrySlug: 'opm',
    status: 'open',
    createdDate: '2026-04-10',
    linkedType: 'action_item',
    linkedName: 'National Digital ID policy framework',
    linkedHref: '/meetings/mtg-2026-04-20',
    activity: [
      { id: 'a3-1', type: 'comment', author: 'Hon. Ambassador Audrey Marks, MP', content: 'NIRA reporting 15.3% false rejection rate in St. Catherine pilot. Vendor acknowledges the issue.', timestamp: '2026-04-10T08:30:00' },
      { id: 'a3-2', type: 'comment', author: 'Hon. Ambassador Audrey Marks, MP', content: 'Vendor committed to patch by April 28. If missed, we need to consider alternative suppliers.', timestamp: '2026-04-18T16:00:00' },
    ],
  },
  {
    id: 'blk-4',
    title: 'JCF recruitment pipeline blocked by delayed salary adjustments',
    description: 'The 2025 police salary adjustment has not been fully implemented in the payroll system. Prospective recruits are being quoted old salary figures, leading to a 34% offer decline rate. 850 approved posts remain unfilled.',
    escalationLevel: 'minister',
    assignedTo: 'Hon. Dr. Horace Chang, OJ, CD, MP',
    assignedMinistrySlug: 'national-security',
    status: 'open',
    createdDate: '2026-03-15',
    linkedType: 'action_item',
    linkedName: 'JCF recruitment targets report',
    linkedHref: '/meetings/mtg-2026-03-23',
    activity: [
      { id: 'a4-1', type: 'comment', author: 'Hon. Dr. Horace Chang, OJ, CD, MP', content: 'JCF HR confirms 34% of conditional offers declined due to salary confusion. Payroll system still showing pre-adjustment figures.', timestamp: '2026-03-15T10:00:00' },
      { id: 'a4-2', type: 'comment', author: 'Hon. Fayval Williams, MP', content: 'MoFPS IT team has been assigned to expedite the payroll update. Estimated completion: April 15.', timestamp: '2026-03-22T14:00:00' },
      { id: 'a4-3', type: 'comment', author: 'Hon. Dr. Horace Chang, OJ, CD, MP', content: 'April 15 deadline missed. Escalating — this is now impacting national security readiness.', timestamp: '2026-04-17T09:30:00' },
    ],
  },
  {
    id: 'blk-5',
    title: 'Agricultural insurance scheme awaiting actuarial review',
    description: 'The proposed small farmer climate insurance scheme cannot proceed to Cabinet approval without a completed actuarial assessment. The contracted actuary has delayed deliverables twice, now citing data quality issues with RADA\'s crop loss records.',
    escalationLevel: 'minister',
    assignedTo: 'Hon. Floyd Green, MP',
    assignedMinistrySlug: 'agriculture',
    status: 'open',
    createdDate: '2026-03-20',
    linkedType: 'action_item',
    linkedName: 'Agricultural insurance scheme proposal',
    linkedHref: '/meetings/mtg-2026-03-16',
    activity: [
      { id: 'a5-1', type: 'comment', author: 'Hon. Floyd Green, MP', content: 'Actuary missed second deadline for the climate insurance assessment. Citing RADA data gaps.', timestamp: '2026-03-20T11:00:00' },
      { id: 'a5-2', type: 'comment', author: 'Hon. Floyd Green, MP', content: 'RADA has assigned a data team to clean up 3 years of crop loss records. Will take ~3 weeks.', timestamp: '2026-04-05T10:00:00' },
    ],
  },
  {
    id: 'blk-6',
    title: 'Vernamfield SEZ environmental impact assessment incomplete',
    description: 'NEPA has not completed the Environmental Impact Assessment for the Vernamfield Special Economic Zone. Without the EIA, the enabling legislation cannot proceed to Parliament and no investor agreements can be signed.',
    escalationLevel: 'minister',
    assignedTo: 'Senator Hon. Aubyn Hill',
    assignedMinistrySlug: 'industry',
    status: 'in_progress',
    createdDate: '2026-02-18',
    linkedType: 'project',
    linkedName: 'Vernamfield SEZ feasibility',
    linkedHref: '/ministry/industry',
    activity: [
      { id: 'a6-1', type: 'comment', author: 'Senator Hon. Aubyn Hill', content: 'NEPA EIA for Vernamfield now 4 months overdue. Blocking all investor discussions.', timestamp: '2026-02-18T09:00:00' },
      { id: 'a6-2', type: 'comment', author: 'Senator Hon. Aubyn Hill', content: 'Met with NEPA CEO. They committed to completing the EIA by end of April.', timestamp: '2026-03-10T15:30:00' },
      { id: 'a6-3', type: 'status_change', author: 'Senator Hon. Aubyn Hill', content: 'Status changed', timestamp: '2026-03-10T15:30:00', previousStatus: 'open', newStatus: 'in_progress' },
      { id: 'a6-4', type: 'comment', author: 'Senator Hon. Aubyn Hill', content: 'NEPA draft EIA received for review. Final version expected May 5.', timestamp: '2026-04-21T10:00:00' },
    ],
  },
  {
    id: 'blk-7',
    title: 'PATH benefits system upgrade failing load tests',
    description: 'The upgraded PATH benefits disbursement system fails under production load conditions. The contractor\'s stress test showed 40% transaction failure rate above 5,000 concurrent users. This blocks the expansion of PATH to cover displaced agricultural workers.',
    escalationLevel: 'minister',
    assignedTo: 'Hon. Pearnel Charles Jr., MP, JP',
    assignedMinistrySlug: 'labour',
    status: 'open',
    createdDate: '2026-04-14',
    linkedType: 'action_item',
    linkedName: 'Expanded PATH benefits proposal',
    linkedHref: '/meetings/mtg-2026-04-13',
    activity: [
      { id: 'a7-1', type: 'comment', author: 'Hon. Pearnel Charles Jr., MP, JP', content: 'Load testing revealed 40% transaction failures. Vendor investigating root cause.', timestamp: '2026-04-14T14:00:00' },
      { id: 'a7-2', type: 'comment', author: 'Hon. Pearnel Charles Jr., MP, JP', content: 'Vendor identified database connection pooling as bottleneck. Fix ETA: April 30.', timestamp: '2026-04-22T09:30:00' },
    ],
  },
  {
    id: 'blk-8',
    title: 'Teacher recruitment programme delayed by HRMIS integration',
    description: 'The Ministry of Education cannot process the 1,200 new teacher hires approved in the budget because the Human Resource Management Information System (HRMIS) has not been updated with the new post classifications. This is blocking the Q3 expenditure projections.',
    escalationLevel: 'minister',
    assignedTo: 'Sen. Dr. the Hon. Dana Morris Dixon',
    assignedMinistrySlug: 'education',
    status: 'resolved',
    createdDate: '2026-03-05',
    linkedType: 'action_item',
    linkedName: 'Revised Q3 expenditure projections',
    linkedHref: '/meetings/mtg-2026-04-20',
    activity: [
      { id: 'a8-1', type: 'comment', author: 'Sen. Dr. the Hon. Dana Morris Dixon', content: 'HRMIS does not have updated post classifications. Cannot process 1,200 new teacher appointments.', timestamp: '2026-03-05T10:00:00' },
      { id: 'a8-2', type: 'comment', author: 'Hon. Fayval Williams, MP', content: 'MoFPS will prioritize HRMIS update for Education. Target: March 31.', timestamp: '2026-03-12T11:00:00' },
      { id: 'a8-3', type: 'comment', author: 'Sen. Dr. the Hon. Dana Morris Dixon', content: 'March 31 deadline missed. Still waiting on HRMIS update.', timestamp: '2026-04-02T09:00:00' },
      { id: 'a8-4', type: 'status_change', author: 'Sen. Dr. the Hon. Dana Morris Dixon', content: 'Status changed', timestamp: '2026-04-10T14:00:00', previousStatus: 'open', newStatus: 'in_progress' },
      { id: 'a8-5', type: 'comment', author: 'Sen. Dr. the Hon. Dana Morris Dixon', content: 'HRMIS updated. First batch of 400 appointments processed. Remaining 800 in progress.', timestamp: '2026-04-10T14:00:00' },
      { id: 'a8-6', type: 'status_change', author: 'Sen. Dr. the Hon. Dana Morris Dixon', content: 'Status changed', timestamp: '2026-04-23T16:00:00', previousStatus: 'in_progress', newStatus: 'resolved' },
      { id: 'a8-7', type: 'comment', author: 'Sen. Dr. the Hon. Dana Morris Dixon', content: 'All 1,200 appointments processed. Q3 projections updated and submitted to Finance.', timestamp: '2026-04-23T16:00:00' },
    ],
  },
];

export function getBlocker(id: string): Blocker | undefined {
  return mockBlockers.find(b => b.id === id);
}
